export const STORE_URL = "https://4geekmenots.etsy.com";

export const collections = [
  { id: "all", label: "All designs" },
  { id: "travel", label: "Travel" },
  { id: "pride", label: "Pride" },
  { id: "mindset", label: "Mindset" },
  { id: "statement", label: "Statement" },
  { id: "culture", label: "Culture" },
  { id: "humor", label: "Humor" },
];

export const products = [
  {
    id: "atl-pride-boarding-pass",
    title: "ATL Pride Boarding Pass Tee",
    image: "/products/atl-boarding-pass.avif",
    fallbackImage: "/img/atl-boarding-pass.png",
    alt: "Red T-shirt with a yellow ATL Pride boarding pass graphic",
    description: "A flight-tag design celebrating Atlanta, chosen family, and joy.",
    collection: "pride",
    collectionLabel: "Pride",
    url: "https://www.etsy.com/listing/4373905476/atl-pride-boarding-pass-t-shirt-flight",
    price: 25.99,
    fulfillment: "printify",
    featured: true,
  },
  {
    id: "travel-love-language",
    title: "Travel Is My Love Language",
    image: "/products/travel-love-language.avif",
    fallbackImage: "/img/travel-love-language.png",
    alt: "T-shirt mockup with a globe and Travel Is My Love Language artwork",
    description: "A clean globe graphic for travelers who are always planning the next trip.",
    collection: "travel",
    collectionLabel: "Travel",
    url: "https://www.etsy.com/listing/4374298621/travel-is-my-love-language-t-shirt-globe",
    price: 25.99,
    fulfillment: "printify",
    featured: true,
  },
  {
    id: "mental-health-wealth-crowned",
    title: "Mental Health Is Wealth",
    image: "/products/mental-health-wealth.avif",
    fallbackImage: "/img/mental-health-wealth.png",
    alt: "T-shirt mockup with crowned Mental Health Is Wealth typography",
    description: "A direct reminder to protect what keeps everything else moving.",
    collection: "mindset",
    collectionLabel: "Mindset",
    url: "https://www.etsy.com/listing/4370730462/mental-health-is-wealth-shirt-crowned",
    price: 25.99,
    fulfillment: "printify",
    featured: true,
  },
  {
    id: "made-ya-look-blm-hat",
    title: "Made Ya Look BLM Hat",
    image: "/products/made-ya-look.avif",
    fallbackImage: "/img/made-ya-look.png",
    alt: "Red cap with Made Ya Look Black Lives Matter typography",
    description: "A minimal cap with a message that refuses to disappear into the background.",
    collection: "statement",
    collectionLabel: "Statement",
    url: "https://www.etsy.com/listing/4385223572/made-ya-look-black-lives-matter",
    price: 30,
    fulfillment: "printify",
  },
  {
    id: "saturday-love-lyrical",
    title: "Our Saturday Love Lyrical Tee",
    image: "/products/saturday-love.avif",
    fallbackImage: "/img/saturday-love.png",
    alt: "T-shirt mockup from the Our Saturday Love lyrical collection",
    description: "A lyric-forward design made for the songs and memories that stay with you.",
    collection: "culture",
    collectionLabel: "Culture",
    url: "https://www.etsy.com/listing/4373226626/our-saturday-love-t-shirt-lyrical-tees",
    price: 25.99,
    fulfillment: "printify",
  },
  {
    id: "atl-pride",
    title: "ATL Pride Tee",
    image: "/products/atl-pride.avif",
    fallbackImage: "/img/atl-pride.png",
    alt: "T-shirt mockup featuring bold Atlanta Pride artwork",
    description: "Atlanta pride, bold color, and a clean graphic built for everyday wear.",
    collection: "pride",
    collectionLabel: "Pride",
    url: "https://www.etsy.com/listing/4373799355/unisex-heavy-cotton-tee",
    price: 25.99,
    fulfillment: "printify",
  },
  {
    id: "equality-division",
    title: "Equality Over Division",
    image: "/products/equality-division.avif",
    fallbackImage: "/img/equality-division.png",
    alt: "T-shirt mockup with Equality greater than Division statement artwork",
    description: "A simple statement with no room for misreading the message.",
    collection: "statement",
    collectionLabel: "Statement",
    url: "https://www.etsy.com/listing/4344693260",
    price: 23.99,
    fulfillment: "printify",
  },
  {
    id: "he-thick-thick",
    title: "He Thick Thick",
    image: "/products/he-thick.avif",
    fallbackImage: "/img/he-thick.png",
    alt: "T-shirt mockup with bold He Thick Thick typography",
    description: "Bold type, playful energy, and a line that lands before you say a word.",
    collection: "culture",
    collectionLabel: "Culture",
    url: "https://www.etsy.com/listing/4362728564/oh-he-thick-thick-funny-bold-typography",
    price: 25.99,
    fulfillment: "printify",
  },
  {
    id: "airplane-mode",
    title: "Airplane Mode",
    image: "/products/airplane-mode.avif",
    fallbackImage: "/img/airplane-mode.png",
    alt: "Travel T-shirt mockup featuring Airplane Mode artwork",
    description: "For non-rev travelers, frequent flyers, and anyone ready to disconnect.",
    collection: "travel",
    collectionLabel: "Travel",
    url: "https://www.etsy.com/listing/4355745827/airplane-mode-shirt-fun-travel-tee",
    price: 25,
    fulfillment: "printify",
  },
  {
    id: "non-rev-barcode",
    title: "Non-Rev Life Barcode",
    image: "/products/non-rev-life-barcode.avif",
    fallbackImage: "/img/non-rev-life-barcode.png",
    alt: "Travel apparel mockup with a Non-Rev Life barcode design",
    description: "A nod to standby warriors, gate changes, and the thrill of an open seat.",
    collection: "travel",
    collectionLabel: "Travel",
    url: "https://www.etsy.com/listing/4362839119",
    price: 39,
    fulfillment: "printify",
  },
  {
    id: "my-bed-is-calling",
    title: "My Bed Is Calling",
    image: "/products/my-bed-is-calling.avif",
    fallbackImage: "/img/my-bed-is-calling.png",
    alt: "T-shirt mockup with My Bed Is Calling artwork",
    description: "For night-shift workers, committed nappers, and professional homebodies.",
    collection: "humor",
    collectionLabel: "Humor",
    url: "https://www.etsy.com/listing/4363335234",
    price: 23.99,
    fulfillment: "printify",
  },
  {
    id: "404-sleep-not-found",
    title: "404: Sleep Not Found",
    image: "/products/404-sleep-not-found.avif",
    fallbackImage: "/img/404-sleep-not-found.png",
    alt: "Geeky T-shirt mockup with 404 Sleep Not Found robot artwork",
    description: "A familiar error for developers, night owls, and overactive minds.",
    collection: "humor",
    collectionLabel: "Humor",
    url: "https://www.etsy.com/listing/4344683685",
    price: 25.99,
    fulfillment: "printify",
  },
  {
    id: "heal-hoodie",
    title: "HEAL Hoodie",
    image: "/products/heal-hoodie.avif",
    fallbackImage: "/img/heal-hoodie.png",
    alt: "Hoodie mockup featuring the HEAL Healthy Emotionally artwork",
    description: "Healthy emotionally, grounded intentionally, and comfortable through the work.",
    collection: "mindset",
    collectionLabel: "Mindset",
    url: "https://www.etsy.com/listing/4362682736",
    price: 35.99,
    fulfillment: "printify",
  },
  {
    id: "certified-rainbow-ally",
    title: "Certified Rainbow Ally",
    image: "/products/certified-rainbow-ally.avif",
    fallbackImage: "/img/certified-rainbow-ally.png",
    alt: "Pride T-shirt mockup with Certified Rainbow Ally artwork",
    description: "A proud, direct design for showing up with love and standing beside community.",
    collection: "pride",
    collectionLabel: "Pride",
    url: "https://www.etsy.com/listing/4355134835",
    price: 25.99,
    fulfillment: "printify",
  },
];
